title: My music
email: 
baseurl: ""
url: "https://tabs.paulc.me"
github_username:  paulcarroll

collections:
  pages:
    output: true

sass:
  sass_dir: _scss
  style:    :compressed

# Build settings
# theme: minima
plugins:
  - jekyll-sass-converter

# exclude:
#   - .sass-cache/
